name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: projet7-deeplearning
  PYTHON_VERSION: '3.10'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsentencepiece-dev pkg-config protobuf-compiler

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: Download NLTK data
        run: |
          python -m nltk.downloader stopwords
          python -m nltk.downloader punkt
          python -m nltk.downloader wordnet

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app/

      - name: Run tests
        run: |
          pytest --maxfail=5
        timeout-minutes: 30

      - name: Create deployment package
        run: |
          zip -r deployment.zip app/ requirements.txt runtime.txt Procfile

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip

      - name: Clean up deployment package
        if: always()
        run: |
          rm -f deployment.zip
