name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: projet7-deeplearning    
  PYTHON_VERSION: '3.8'  # Version plus stable pour Azure Web Apps

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install --no-cache-dir -r requirements.txt

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_45490A570B0B4C19A6319C6754C6AF59 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C16F1A47DD7145C392A1511930503CF6 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FE86E32938034540BC0A89D83862C25F }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Ajoutez ce secret dans GitHub
        package: .

    - name: Verify deployment
      run: |
        echo "Deployed to ${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net"
        curl -sSf https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/ || echo "Application deployed but endpoint not responding yet"